[tox]
envlist = pylint,pylint-test,p310,p311

[testenv]
deps = .[tests]
setenv = PYTHONPATH=.
commands = python -m unittest discover

[testenv:pylint]
deps = pylint
       .[tests]
commands = pylint cnam

[testenv:pylint-test]
deps = pylint
       .[tests]
commands = pylint --rcfile testdir.pylintrc --errors-only tests/

[testenv:testsacc]
deps = robotframework
       .[tests]
commands = robot testsacc